import Foundation

// MARK: - Notification Names

extension Notification.Name {
    /// Posted when a streaming text chunk arrives.
    /// UserInfo keys: "agentPubkey", "conversationId", "textDelta" (optional)
    static let tenexStreamChunk = Notification.Name("tenexStreamChunk")
}

// MARK: - Event Handler

/// Handles event callbacks from Rust core and applies deltas to TenexCoreManager.
/// Stream chunks are still dispatched via NotificationCenter for active viewers.
/// Implements the EventCallback protocol generated by UniFFI.
///
/// Thread Safety: Callbacks are invoked from a background thread in Rust.
/// This handler dispatches all notifications to the main thread for safe UI updates.
final class TenexEventHandler: EventCallback {
    weak var coreManager: TenexCoreManager?

    init(coreManager: TenexCoreManager) {
        self.coreManager = coreManager
    }

    func onDataChanged(changeType: DataChangeType) {
        Task { @MainActor [weak self] in
            guard let coreManager = self?.coreManager else { return }

            switch changeType {
            case .messageAppended(let conversationId, _):
                coreManager.signalConversationUpdate(conversationId: conversationId)

            case .conversationUpsert(let conversation):
                coreManager.signalConversationUpdate(conversationId: conversation.id)

            case .projectUpsert:
                coreManager.signalGeneralUpdate()

            case .inboxUpsert:
                coreManager.signalGeneralUpdate()

            case .projectStatusChanged:
                coreManager.signalProjectStatusUpdate()

            case .pendingBackendApproval:
                coreManager.signalGeneralUpdate()

            case .activeConversationsChanged:
                coreManager.signalGeneralUpdate()

            case .streamChunk(let agentPubkey, let conversationId, let textDelta):
                NotificationCenter.default.post(
                    name: .tenexStreamChunk,
                    object: nil,
                    userInfo: [
                        "agentPubkey": agentPubkey,
                        "conversationId": conversationId,
                        "textDelta": textDelta as Any
                    ]
                )

            case .mcpToolsChanged:
                coreManager.signalGeneralUpdate()

            case .statsUpdated:
                coreManager.signalGeneralUpdate()

            case .diagnosticsUpdated:
                coreManager.signalGeneralUpdate()

            case .general:
                coreManager.signalGeneralUpdate()
            }
        }
    }
}
