// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(tenex_coreFFI)
import tenex_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_tenex_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_tenex_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTenexCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Core TENEX functionality exposed to foreign languages.
 *
 * This is intentionally minimal for MVP - we'll expand as needed.
 * Note: UniFFI objects are wrapped in Arc, so we use AtomicBool for interior mutability.
 */
public protocol TenexCoreProtocol: AnyObject, Sendable {
    
    /**
     * Get conversations for a project.
     *
     * Returns conversations organized with parent/child relationships.
     * Use parent_id to build nested conversation trees.
     */
    func getConversations(projectId: String)  -> [ConversationInfo]
    
    /**
     * Get information about the currently logged-in user.
     *
     * Returns None if not logged in.
     */
    func getCurrentUser()  -> UserInfo?
    
    /**
     * Get inbox items for the current user.
     */
    func getInbox()  -> [InboxItem]
    
    /**
     * Get messages for a conversation.
     */
    func getMessages(conversationId: String)  -> [MessageInfo]
    
    /**
     * Get a list of projects.
     *
     * In the full implementation, this would:
     * 1. Query nostrdb for kind 31933 events
     * 2. Parse them into Project structs
     * 3. Convert to ProjectInfo for FFI
     *
     * For MVP, returns sample hardcoded projects to demonstrate the UI.
     */
    func getProjects()  -> [ProjectInfo]
    
    /**
     * Get reports for a project.
     */
    func getReports(projectId: String)  -> [ReportInfo]
    
    /**
     * Initialize the core. Must be called before other operations.
     * Returns true if initialization succeeded.
     */
    func `init`()  -> Bool
    
    /**
     * Check if the core is initialized.
     */
    func isInitialized()  -> Bool
    
    /**
     * Check if a user is currently logged in.
     */
    func isLoggedIn()  -> Bool
    
    /**
     * Login with an nsec (Nostr secret key in bech32 format).
     *
     * The nsec should be in the format `nsec1...`.
     * On success, stores the keys for subsequent operations.
     */
    func login(nsec: String) throws  -> LoginResult
    
    /**
     * Logout the current user.
     */
    func logout() 
    
    /**
     * Get the version of tenex-core.
     */
    func version()  -> String
    
}
/**
 * Core TENEX functionality exposed to foreign languages.
 *
 * This is intentionally minimal for MVP - we'll expand as needed.
 * Note: UniFFI objects are wrapped in Arc, so we use AtomicBool for interior mutability.
 */
open class TenexCore: TenexCoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_tenex_core_fn_clone_tenexcore(self.pointer, $0) }
    }
    /**
     * Create a new TenexCore instance.
     * This is the entry point for the FFI API.
     */
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_tenex_core_fn_constructor_tenexcore_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_tenex_core_fn_free_tenexcore(pointer, $0) }
    }

    

    
    /**
     * Get conversations for a project.
     *
     * Returns conversations organized with parent/child relationships.
     * Use parent_id to build nested conversation trees.
     */
open func getConversations(projectId: String) -> [ConversationInfo]  {
    return try!  FfiConverterSequenceTypeConversationInfo.lift(try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_get_conversations(self.uniffiClonePointer(),
        FfiConverterString.lower(projectId),$0
    )
})
}
    
    /**
     * Get information about the currently logged-in user.
     *
     * Returns None if not logged in.
     */
open func getCurrentUser() -> UserInfo?  {
    return try!  FfiConverterOptionTypeUserInfo.lift(try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_get_current_user(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get inbox items for the current user.
     */
open func getInbox() -> [InboxItem]  {
    return try!  FfiConverterSequenceTypeInboxItem.lift(try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_get_inbox(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get messages for a conversation.
     */
open func getMessages(conversationId: String) -> [MessageInfo]  {
    return try!  FfiConverterSequenceTypeMessageInfo.lift(try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_get_messages(self.uniffiClonePointer(),
        FfiConverterString.lower(conversationId),$0
    )
})
}
    
    /**
     * Get a list of projects.
     *
     * In the full implementation, this would:
     * 1. Query nostrdb for kind 31933 events
     * 2. Parse them into Project structs
     * 3. Convert to ProjectInfo for FFI
     *
     * For MVP, returns sample hardcoded projects to demonstrate the UI.
     */
open func getProjects() -> [ProjectInfo]  {
    return try!  FfiConverterSequenceTypeProjectInfo.lift(try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_get_projects(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get reports for a project.
     */
open func getReports(projectId: String) -> [ReportInfo]  {
    return try!  FfiConverterSequenceTypeReportInfo.lift(try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_get_reports(self.uniffiClonePointer(),
        FfiConverterString.lower(projectId),$0
    )
})
}
    
    /**
     * Initialize the core. Must be called before other operations.
     * Returns true if initialization succeeded.
     */
open func `init`() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_init(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Check if the core is initialized.
     */
open func isInitialized() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_is_initialized(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Check if a user is currently logged in.
     */
open func isLoggedIn() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_is_logged_in(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Login with an nsec (Nostr secret key in bech32 format).
     *
     * The nsec should be in the format `nsec1...`.
     * On success, stores the keys for subsequent operations.
     */
open func login(nsec: String)throws  -> LoginResult  {
    return try  FfiConverterTypeLoginResult_lift(try rustCallWithError(FfiConverterTypeTenexError_lift) {
    uniffi_tenex_core_fn_method_tenexcore_login(self.uniffiClonePointer(),
        FfiConverterString.lower(nsec),$0
    )
})
}
    
    /**
     * Logout the current user.
     */
open func logout()  {try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_logout(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Get the version of tenex-core.
     */
open func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_tenex_core_fn_method_tenexcore_version(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTenexCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = TenexCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> TenexCore {
        return TenexCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: TenexCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TenexCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: TenexCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTenexCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> TenexCore {
    return try FfiConverterTypeTenexCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTenexCore_lower(_ value: TenexCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTenexCore.lower(value)
}




/**
 * A conversation/thread in a project.
 */
public struct ConversationInfo {
    /**
     * Unique identifier of the conversation (event ID)
     */
    public var id: String
    /**
     * Title/subject of the conversation
     */
    public var title: String
    /**
     * Agent or user who started the conversation
     */
    public var author: String
    /**
     * Brief summary or first line of content
     */
    public var summary: String?
    /**
     * Number of messages in the thread
     */
    public var messageCount: UInt32
    /**
     * Unix timestamp of last activity
     */
    public var lastActivity: UInt64
    /**
     * Parent conversation ID (for nesting)
     */
    public var parentId: String?
    /**
     * Status: active, completed, waiting
     */
    public var status: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Unique identifier of the conversation (event ID)
         */id: String, 
        /**
         * Title/subject of the conversation
         */title: String, 
        /**
         * Agent or user who started the conversation
         */author: String, 
        /**
         * Brief summary or first line of content
         */summary: String?, 
        /**
         * Number of messages in the thread
         */messageCount: UInt32, 
        /**
         * Unix timestamp of last activity
         */lastActivity: UInt64, 
        /**
         * Parent conversation ID (for nesting)
         */parentId: String?, 
        /**
         * Status: active, completed, waiting
         */status: String) {
        self.id = id
        self.title = title
        self.author = author
        self.summary = summary
        self.messageCount = messageCount
        self.lastActivity = lastActivity
        self.parentId = parentId
        self.status = status
    }
}

#if compiler(>=6)
extension ConversationInfo: Sendable {}
#endif


extension ConversationInfo: Equatable, Hashable {
    public static func ==(lhs: ConversationInfo, rhs: ConversationInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.author != rhs.author {
            return false
        }
        if lhs.summary != rhs.summary {
            return false
        }
        if lhs.messageCount != rhs.messageCount {
            return false
        }
        if lhs.lastActivity != rhs.lastActivity {
            return false
        }
        if lhs.parentId != rhs.parentId {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(title)
        hasher.combine(author)
        hasher.combine(summary)
        hasher.combine(messageCount)
        hasher.combine(lastActivity)
        hasher.combine(parentId)
        hasher.combine(status)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConversationInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConversationInfo {
        return
            try ConversationInfo(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                author: FfiConverterString.read(from: &buf), 
                summary: FfiConverterOptionString.read(from: &buf), 
                messageCount: FfiConverterUInt32.read(from: &buf), 
                lastActivity: FfiConverterUInt64.read(from: &buf), 
                parentId: FfiConverterOptionString.read(from: &buf), 
                status: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ConversationInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.author, into: &buf)
        FfiConverterOptionString.write(value.summary, into: &buf)
        FfiConverterUInt32.write(value.messageCount, into: &buf)
        FfiConverterUInt64.write(value.lastActivity, into: &buf)
        FfiConverterOptionString.write(value.parentId, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConversationInfo_lift(_ buf: RustBuffer) throws -> ConversationInfo {
    return try FfiConverterTypeConversationInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConversationInfo_lower(_ value: ConversationInfo) -> RustBuffer {
    return FfiConverterTypeConversationInfo.lower(value)
}


/**
 * An inbox item (task/notification waiting for attention).
 */
public struct InboxItem {
    /**
     * Unique identifier
     */
    public var id: String
    /**
     * Title/summary of the item
     */
    public var title: String
    /**
     * Detailed content
     */
    public var content: String
    /**
     * Who it's from
     */
    public var fromAgent: String
    /**
     * Priority: high, medium, low
     */
    public var priority: String
    /**
     * Status: waiting, acknowledged, resolved
     */
    public var status: String
    /**
     * Unix timestamp
     */
    public var createdAt: UInt64
    /**
     * Related project ID
     */
    public var projectId: String?
    /**
     * Related conversation ID
     */
    public var conversationId: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Unique identifier
         */id: String, 
        /**
         * Title/summary of the item
         */title: String, 
        /**
         * Detailed content
         */content: String, 
        /**
         * Who it's from
         */fromAgent: String, 
        /**
         * Priority: high, medium, low
         */priority: String, 
        /**
         * Status: waiting, acknowledged, resolved
         */status: String, 
        /**
         * Unix timestamp
         */createdAt: UInt64, 
        /**
         * Related project ID
         */projectId: String?, 
        /**
         * Related conversation ID
         */conversationId: String?) {
        self.id = id
        self.title = title
        self.content = content
        self.fromAgent = fromAgent
        self.priority = priority
        self.status = status
        self.createdAt = createdAt
        self.projectId = projectId
        self.conversationId = conversationId
    }
}

#if compiler(>=6)
extension InboxItem: Sendable {}
#endif


extension InboxItem: Equatable, Hashable {
    public static func ==(lhs: InboxItem, rhs: InboxItem) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        if lhs.fromAgent != rhs.fromAgent {
            return false
        }
        if lhs.priority != rhs.priority {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.projectId != rhs.projectId {
            return false
        }
        if lhs.conversationId != rhs.conversationId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(title)
        hasher.combine(content)
        hasher.combine(fromAgent)
        hasher.combine(priority)
        hasher.combine(status)
        hasher.combine(createdAt)
        hasher.combine(projectId)
        hasher.combine(conversationId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInboxItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InboxItem {
        return
            try InboxItem(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                fromAgent: FfiConverterString.read(from: &buf), 
                priority: FfiConverterString.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterUInt64.read(from: &buf), 
                projectId: FfiConverterOptionString.read(from: &buf), 
                conversationId: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: InboxItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterString.write(value.fromAgent, into: &buf)
        FfiConverterString.write(value.priority, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterUInt64.write(value.createdAt, into: &buf)
        FfiConverterOptionString.write(value.projectId, into: &buf)
        FfiConverterOptionString.write(value.conversationId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInboxItem_lift(_ buf: RustBuffer) throws -> InboxItem {
    return try FfiConverterTypeInboxItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInboxItem_lower(_ value: InboxItem) -> RustBuffer {
    return FfiConverterTypeInboxItem.lower(value)
}


/**
 * Result of a successful login operation.
 */
public struct LoginResult {
    /**
     * Hex-encoded public key
     */
    public var pubkey: String
    /**
     * Bech32-encoded public key (npub1...)
     */
    public var npub: String
    /**
     * Whether login was successful
     */
    public var success: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hex-encoded public key
         */pubkey: String, 
        /**
         * Bech32-encoded public key (npub1...)
         */npub: String, 
        /**
         * Whether login was successful
         */success: Bool) {
        self.pubkey = pubkey
        self.npub = npub
        self.success = success
    }
}

#if compiler(>=6)
extension LoginResult: Sendable {}
#endif


extension LoginResult: Equatable, Hashable {
    public static func ==(lhs: LoginResult, rhs: LoginResult) -> Bool {
        if lhs.pubkey != rhs.pubkey {
            return false
        }
        if lhs.npub != rhs.npub {
            return false
        }
        if lhs.success != rhs.success {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pubkey)
        hasher.combine(npub)
        hasher.combine(success)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLoginResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LoginResult {
        return
            try LoginResult(
                pubkey: FfiConverterString.read(from: &buf), 
                npub: FfiConverterString.read(from: &buf), 
                success: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: LoginResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterString.write(value.npub, into: &buf)
        FfiConverterBool.write(value.success, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginResult_lift(_ buf: RustBuffer) throws -> LoginResult {
    return try FfiConverterTypeLoginResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginResult_lower(_ value: LoginResult) -> RustBuffer {
    return FfiConverterTypeLoginResult.lower(value)
}


/**
 * A message within a conversation.
 */
public struct MessageInfo {
    /**
     * Unique identifier of the message (event ID)
     */
    public var id: String
    /**
     * Content of the message (can be markdown)
     */
    public var content: String
    /**
     * Author name/identifier
     */
    public var author: String
    /**
     * Author's npub
     */
    public var authorNpub: String
    /**
     * Unix timestamp when message was created
     */
    public var createdAt: UInt64
    /**
     * Whether this is a tool call
     */
    public var isToolCall: Bool
    /**
     * Role: user, assistant, system
     */
    public var role: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Unique identifier of the message (event ID)
         */id: String, 
        /**
         * Content of the message (can be markdown)
         */content: String, 
        /**
         * Author name/identifier
         */author: String, 
        /**
         * Author's npub
         */authorNpub: String, 
        /**
         * Unix timestamp when message was created
         */createdAt: UInt64, 
        /**
         * Whether this is a tool call
         */isToolCall: Bool, 
        /**
         * Role: user, assistant, system
         */role: String) {
        self.id = id
        self.content = content
        self.author = author
        self.authorNpub = authorNpub
        self.createdAt = createdAt
        self.isToolCall = isToolCall
        self.role = role
    }
}

#if compiler(>=6)
extension MessageInfo: Sendable {}
#endif


extension MessageInfo: Equatable, Hashable {
    public static func ==(lhs: MessageInfo, rhs: MessageInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        if lhs.author != rhs.author {
            return false
        }
        if lhs.authorNpub != rhs.authorNpub {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.isToolCall != rhs.isToolCall {
            return false
        }
        if lhs.role != rhs.role {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(content)
        hasher.combine(author)
        hasher.combine(authorNpub)
        hasher.combine(createdAt)
        hasher.combine(isToolCall)
        hasher.combine(role)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessageInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MessageInfo {
        return
            try MessageInfo(
                id: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                author: FfiConverterString.read(from: &buf), 
                authorNpub: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterUInt64.read(from: &buf), 
                isToolCall: FfiConverterBool.read(from: &buf), 
                role: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MessageInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterString.write(value.author, into: &buf)
        FfiConverterString.write(value.authorNpub, into: &buf)
        FfiConverterUInt64.write(value.createdAt, into: &buf)
        FfiConverterBool.write(value.isToolCall, into: &buf)
        FfiConverterString.write(value.role, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageInfo_lift(_ buf: RustBuffer) throws -> MessageInfo {
    return try FfiConverterTypeMessageInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageInfo_lower(_ value: MessageInfo) -> RustBuffer {
    return FfiConverterTypeMessageInfo.lower(value)
}


/**
 * A simplified project info struct for FFI export.
 * This is a subset of the full Project model, safe for cross-language use.
 */
public struct ProjectInfo {
    /**
     * Unique identifier (d-tag) of the project
     */
    public var id: String
    /**
     * Display name/title of the project
     */
    public var title: String
    /**
     * Project description (from content field), if any
     */
    public var description: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Unique identifier (d-tag) of the project
         */id: String, 
        /**
         * Display name/title of the project
         */title: String, 
        /**
         * Project description (from content field), if any
         */description: String?) {
        self.id = id
        self.title = title
        self.description = description
    }
}

#if compiler(>=6)
extension ProjectInfo: Sendable {}
#endif


extension ProjectInfo: Equatable, Hashable {
    public static func ==(lhs: ProjectInfo, rhs: ProjectInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(title)
        hasher.combine(description)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProjectInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProjectInfo {
        return
            try ProjectInfo(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                description: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ProjectInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterOptionString.write(value.description, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProjectInfo_lift(_ buf: RustBuffer) throws -> ProjectInfo {
    return try FfiConverterTypeProjectInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProjectInfo_lower(_ value: ProjectInfo) -> RustBuffer {
    return FfiConverterTypeProjectInfo.lower(value)
}


/**
 * A report/article in a project (kind 30023 NIP-23 long-form content).
 */
public struct ReportInfo {
    /**
     * Unique identifier (d-tag/slug)
     */
    public var id: String
    /**
     * Title of the report
     */
    public var title: String
    /**
     * Summary/excerpt
     */
    public var summary: String?
    /**
     * Full markdown content
     */
    public var content: String
    /**
     * Author name
     */
    public var author: String
    /**
     * Author npub
     */
    public var authorNpub: String
    /**
     * Unix timestamp of creation
     */
    public var createdAt: UInt64
    /**
     * Unix timestamp of last update
     */
    public var updatedAt: UInt64
    /**
     * Tags/hashtags
     */
    public var tags: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Unique identifier (d-tag/slug)
         */id: String, 
        /**
         * Title of the report
         */title: String, 
        /**
         * Summary/excerpt
         */summary: String?, 
        /**
         * Full markdown content
         */content: String, 
        /**
         * Author name
         */author: String, 
        /**
         * Author npub
         */authorNpub: String, 
        /**
         * Unix timestamp of creation
         */createdAt: UInt64, 
        /**
         * Unix timestamp of last update
         */updatedAt: UInt64, 
        /**
         * Tags/hashtags
         */tags: [String]) {
        self.id = id
        self.title = title
        self.summary = summary
        self.content = content
        self.author = author
        self.authorNpub = authorNpub
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.tags = tags
    }
}

#if compiler(>=6)
extension ReportInfo: Sendable {}
#endif


extension ReportInfo: Equatable, Hashable {
    public static func ==(lhs: ReportInfo, rhs: ReportInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.summary != rhs.summary {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        if lhs.author != rhs.author {
            return false
        }
        if lhs.authorNpub != rhs.authorNpub {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.updatedAt != rhs.updatedAt {
            return false
        }
        if lhs.tags != rhs.tags {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(title)
        hasher.combine(summary)
        hasher.combine(content)
        hasher.combine(author)
        hasher.combine(authorNpub)
        hasher.combine(createdAt)
        hasher.combine(updatedAt)
        hasher.combine(tags)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReportInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReportInfo {
        return
            try ReportInfo(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                summary: FfiConverterOptionString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                author: FfiConverterString.read(from: &buf), 
                authorNpub: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterUInt64.read(from: &buf), 
                updatedAt: FfiConverterUInt64.read(from: &buf), 
                tags: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: ReportInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterOptionString.write(value.summary, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterString.write(value.author, into: &buf)
        FfiConverterString.write(value.authorNpub, into: &buf)
        FfiConverterUInt64.write(value.createdAt, into: &buf)
        FfiConverterUInt64.write(value.updatedAt, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReportInfo_lift(_ buf: RustBuffer) throws -> ReportInfo {
    return try FfiConverterTypeReportInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReportInfo_lower(_ value: ReportInfo) -> RustBuffer {
    return FfiConverterTypeReportInfo.lower(value)
}


/**
 * Information about the current logged-in user.
 */
public struct UserInfo {
    /**
     * Hex-encoded public key
     */
    public var pubkey: String
    /**
     * Bech32-encoded public key (npub1...)
     */
    public var npub: String
    /**
     * Display name (empty for now, can be fetched from profile later)
     */
    public var displayName: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hex-encoded public key
         */pubkey: String, 
        /**
         * Bech32-encoded public key (npub1...)
         */npub: String, 
        /**
         * Display name (empty for now, can be fetched from profile later)
         */displayName: String) {
        self.pubkey = pubkey
        self.npub = npub
        self.displayName = displayName
    }
}

#if compiler(>=6)
extension UserInfo: Sendable {}
#endif


extension UserInfo: Equatable, Hashable {
    public static func ==(lhs: UserInfo, rhs: UserInfo) -> Bool {
        if lhs.pubkey != rhs.pubkey {
            return false
        }
        if lhs.npub != rhs.npub {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pubkey)
        hasher.combine(npub)
        hasher.combine(displayName)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUserInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserInfo {
        return
            try UserInfo(
                pubkey: FfiConverterString.read(from: &buf), 
                npub: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: UserInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterString.write(value.npub, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserInfo_lift(_ buf: RustBuffer) throws -> UserInfo {
    return try FfiConverterTypeUserInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserInfo_lower(_ value: UserInfo) -> RustBuffer {
    return FfiConverterTypeUserInfo.lower(value)
}


/**
 * Errors that can occur during TENEX operations.
 */
public enum TenexError: Swift.Error {

    
    
    case InvalidNsec(message: String
    )
    case NotLoggedIn
    case Internal(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTenexError: FfiConverterRustBuffer {
    typealias SwiftType = TenexError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TenexError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidNsec(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotLoggedIn
        case 3: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TenexError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidNsec(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case .NotLoggedIn:
            writeInt(&buf, Int32(2))
        
        
        case let .Internal(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTenexError_lift(_ buf: RustBuffer) throws -> TenexError {
    return try FfiConverterTypeTenexError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTenexError_lower(_ value: TenexError) -> RustBuffer {
    return FfiConverterTypeTenexError.lower(value)
}


extension TenexError: Equatable, Hashable {}




extension TenexError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeUserInfo: FfiConverterRustBuffer {
    typealias SwiftType = UserInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeUserInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeUserInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeConversationInfo: FfiConverterRustBuffer {
    typealias SwiftType = [ConversationInfo]

    public static func write(_ value: [ConversationInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeConversationInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ConversationInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [ConversationInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeConversationInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeInboxItem: FfiConverterRustBuffer {
    typealias SwiftType = [InboxItem]

    public static func write(_ value: [InboxItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeInboxItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [InboxItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [InboxItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeInboxItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMessageInfo: FfiConverterRustBuffer {
    typealias SwiftType = [MessageInfo]

    public static func write(_ value: [MessageInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMessageInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MessageInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [MessageInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMessageInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeProjectInfo: FfiConverterRustBuffer {
    typealias SwiftType = [ProjectInfo]

    public static func write(_ value: [ProjectInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeProjectInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ProjectInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [ProjectInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeProjectInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeReportInfo: FfiConverterRustBuffer {
    typealias SwiftType = [ReportInfo]

    public static func write(_ value: [ReportInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeReportInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ReportInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [ReportInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeReportInfo.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_tenex_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_get_conversations() != 60701) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_get_current_user() != 48890) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_get_inbox() != 40776) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_get_messages() != 60952) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_get_projects() != 57687) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_get_reports() != 28510) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_init() != 23136) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_is_initialized() != 41100) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_is_logged_in() != 10328) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_login() != 1616) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_logout() != 63727) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_method_tenexcore_version() != 63230) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_core_checksum_constructor_tenexcore_new() != 16430) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTenexCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all